name: health_surveillance_system
description: A Smart Health Surveillance and Early Warning System for water-borne diseases

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.1.0
  animated_text_kit: ^4.2.2
  google_fonts: ^6.1.0
  url_launcher: ^6.1.11
  device_apps: ^2.2.0  # Keep this version as it exists
  flutter_inappwebview: ^5.7.0  # Use a stable version
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  translator: ^1.0.4+1
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.5.3
  http: 1.5.0
  firebase_database: ^12.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true